version: '3.8'
services:

  ecommerce_api:
    container_name: ec_api
    build:
      context: .
      dockerfile: ./ecommerce/Dockerfile
    restart: always
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - DEBUG=False
      - ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - AWS_KEY_ID=${AWS_KEY_ID}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
    volumes:
      - static-data:/vol/app
    ports:
      - 8000:8000
    depends_on:
      - ecommerce_db

  ecommerce_db:
    container_name: ec_db
    image: mysql:5.7.22
    restart: always
    environment:
      - MYSQL_DATABASE=django_admin
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - ./ecommerce/.dbdata:/var/lib/mysql
    ports:
      - 33069:3306

  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - ecommerce_api
    ports:
      - 8004:8000
    volumes:
      - static-data:/vol/static

volumes:
  static-data:

