version: '3.8'
services:

  ecommerce_api:
    container_name: djec_api
    build:
      context: .
      dockerfile: ./ecommerce/Dockerfile
    volumes:
      - ./ecommerce/.:/app
    ports:
      - 8000:8000
    command: >
      sh -c "
            python manage.py wait_db &&
            python manage.py makemigrations user &&
            python manage.py makemigrations products &&
            python manage.py makemigrations orders &&
            python manage.py makemigrations core &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=1
    depends_on:
      - ecommerce_db

  ecommerce_db:
    container_name: ec_db
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - 5435:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
