# Generated by Django 2.2.3 on 2019-08-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryproducts',
            name='active_html',
            field=models.BooleanField(default=False),
        ),
    ]
