# Generated by Django 2.2.3 on 2019-08-11 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_categoryproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='products.CategoryProducts'),
        ),
    ]
