# Generated by Django 2.2.3 on 2019-08-11 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryProducts',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='categories.CategoryProducts'),
        ),
    ]
